src/commands.ts, src/extension.ts, src/stripeWorkspaceState.ts, src/test/mocks/vscode.ts, src/test/suite/commands.test.ts, src/test/suite/stripeWorkspaceState.test.ts, src/test/suite/utils.test.ts, src/utils.ts
Adding a feature that allows recently triggered events to show up on top of the quickpick view. 
As of Rev 3: Recent Events is scoped to the events triggered through the VSCode extension. This will exclude all events triggered manually by the CLI.
In the entry of the workspace state, I set a hard limit of 100 because I figured we wouldn't gain much by storing more than that, and we want a method of cleaning out the data.
=> Recently used events appear on top of Trigger Events command (#77)

src/stripeClient.ts, src/test/suite/stripeClient.test.ts
@stripe/developer-products 
Add tests that verify that `StripeClient` can detect when the CLI is installed at the default path.
In preparation for fixing https://github.com/stripe/vscode-stripe/issues/133, which involves detecting that the CLI is installed at a custom path.
Verify that the tests are testing the right thing by intentionally causing them to fail, then succeed.
=> Add tests for detecting the user has the CLI installed at the default path

src/commands.ts, src/extension.ts, src/stripeClient.ts, src/stripeDebugProvider.ts, src/stripeLanguageServer/client.ts, src/stripeLinter.ts, src/telemetry.ts, src/test/suite/stripeClient.test.ts, src/test/suite/telemetry.test.ts
This PR converts the Telemetry class into an interface and consolidates the responsibility of creating a telemetry instance to the extensions class. This paves the way for [#131](https://github.com/stripe/vscode-stripe/issues/131). In this commit, we prevent the stripeClient unit tests from emitting data to Google Analytics by passing in a NoOp.
Commands and StripeLinter will be updated in a following PR. Those are a bit trickier to untangle.
=> Adding ability to inject specific implementations of Telemetry into unit tests

src/commands.ts, src/extension.ts, src/test/suite/commands.test.ts
This commit converts the Commands module into a class so that we can inject instances of telemetry and stripeTerminal. This has the benefit of making unit testing this class a bit easier, and of course allowing the caller to control which instance of telemetry to use under different circumstances. 
I manually tested all the commands in debug mode. It should be easier to add more unit tests from now on, I started with a few for the commands class for now.
=> Injecting instance of Telemetry into Commands

src/stripeTerminal.ts, src/test/suite/stripeTerminal.test.ts
cc @stripe/developer-products @tjfontaine-stripe @auchenberg-stripe 
Remove detecting if the user has run `stripe` commands in their vscode terminals manually. This undoes https://github.com/stripe/vscode-stripe/issues/55.
After discussions about how to handle detecting if a user is running Stripe CLI commands manually, we determined that this is a difficult problem that can easily lead to issues on the user's system:
- A user's `stripe` command may not be the CLI. We have no idea what killing their `stripe` process would do.
- Our solution to this may not be portable, potentially requiring a code path for each OS. We would need an extra dependency just to handle this if we wanted to avoid that.
As it currently stands, the behavior we wanted to land is not necessarily part of the core …
=> Ignore the user's VS Code terminals that are running `stripe`

README.md, src/extension.ts, src/stripeLinter.ts, src/test/suite/stripeLinter.test.ts
Note about the ReadME Update: If you have the Stripe extension turned on for all workspaces (which I think is the default), it runs the linter on this repo which will be unhappy about the test I just added.
=> Updating StripeLinter to take in an instance of telemetry and adding unit tests

.vscode/launch.json, README.md, src/extension.ts, src/test/runTest.ts
Replaced with a local version of telemetry that emits logs to the console:
I know the possibility of setting NODE_ENV = 'development' was mentioned but I thought it would be safer to explicitly set our own variable to use. NODE_ENV looks like a common env_var and I worry that it could be set as 'development' just because our users are using our extension while they are developing. The sessionID check is a backup in case we forget to add the special flag for whatever reason. Though, please do let know me know if there is a more robust way to do this.
=> Disabling telemetry during in extension development mode

src/surveyPrompt.ts
This should address https://github.com/stripe/vscode-stripe/issues/143
Changing this to an arrow function means `this` will always be in context of our SurveyPrompt class. Before, it would be in context of whoever called this showSurvey() function which is from within the `setTimeout` function, I believe. 
1. I removed the timeout and random assignment of the survey to force the survey to show up.
2. Without this change, the we silently fail on this line `this.storage.update(StorageKeys.lastSurveyDate, currentEpoch);`
3. With this change, we persist the data. Clicking "Take survey" and then re-starting the run a second time results in no survey being prompted.
=> Fixing issue with SurveyPrompt not persisting data in extension context

src/stripeClient.ts, src/test/suite/stripeClient.test.ts
Listen for changes to `stripe` settings. If the user changes their `stripe.cliInstallPath`, we re-detect if they have the CLI installed there and prompt accordingly if they don't.
This required a little bit of refactoring, including changing the side effects that `detectInstalled()` produces.
Examples:
The `stripe.cliInstallPath` setting is not specified and the CLI isn't installed; prompt install.
The `stripe.cliInstallPath` setting is specified, but the CLI isn't installed there; show error.
The `stripe.cliInstallPath` setting is specified and the CLI is there (I moved it from `stripe` -> `stripe2`); no error.
After #135, we have started respecting the user's `stripe.cliInstallPath` setting. This would work as intended on extension activation, but not if a …
=> Prompt user to install CLI or show error message on configuration change

src/extension.ts, src/stripeClient.ts, src/stripeTerminal.ts, src/test/suite/stripeClient.test.ts, src/test/suite/stripeTerminal.test.ts
Instead of using the string `stripe`, use the full path to the CLI executable to run Stripe commands in the vscode terminal. We already use this path when detecting if the user has the CLI installed. This also means our commands will use the user's `stripe.cliInstallPath` setting if they set a custom path.
To achieve this, we made `StripeTerminal` depend on `StripeClient` and added a public method to `StripeClient` to get the CLI path.
Screenshots:
Clicked **Start API logs streaming**; default path was used.
Clicked **Start API logs streaming**; custom path was used.
Clicked **Start API logs streaming** but CLI wasn't installed; prompt for install.
Clicked **Start API logs streaming** but CLI wasn't at custom path; show error message.
A user can still listen …
=> Run commands in vscode terminal with full path to CLI

src/extension.ts, src/git.ts, src/stripeLinter.ts, src/test/suite/git.test.ts, src/test/suite/stripeLinter.test.ts
@stripe/developer-products 
To check if the user is using git, check if the workspace root contains a `.git` folder rather than checking if the vscode git extension is enabled.
We put git-related logic in a new `Git` class and have the `StripeLinter` depend on it. A little bit of refactoring in `StripeLinter` was needed to achieve this.
This does not completely remove the dependency on the vscode git extension because we are still using it to check for which files to lint, but this will be fixed in the next PR.
We want to know if the user is using git because we want show different error messages with our linter, but we want to do it without depending on the user having the vscode git extension.
- Added tests for the `Git` class to verify it recognizes a workspace with and without a …
=> Create Git class to check if the user's workspace is using git

package.json, src/git.ts, src/stripeLinter.ts, src/test/suite/stripeLinter.test.ts
- Before: We depend on the user having the git vscode extension installed in order to check if a file should be linted or not.
- After: Don't use the git vscode extension to check if a file should be linted. Instead, check if the file is ignored by spawning a child process with `git check-ignore <file>`. If ignored, don't lint.
- Fixes #96, where API keys that are already committed are not being linted.
- Also removes a dependency on the git vscode extension.
- Updated linter tests
- Unsure how to test the `isIgnored` method in isolation, so tested manually
- Verified manually that API keys that are already committed are linted, and git-ignored files are not linted
=> Check if file is git-ignored before linting

src/stripeClient.ts, src/test/suite/stripeClient.test.ts
Added two methods to `StripeClient`:
- `getOrCreateStripeProcess: (StripeProcess) => Promise<ChildProcess>`
-  Spawns a "singleton" child process running a stripe CLI command (currently only supports `stripe logs tail`).
- `endStripeProcess: (StripeProcess) => void`
- Ends the process if it exists
These methods will be used in `StripeLogsView` in a separate PR in order to stream logs in the UI.
From #84, we want to stream logs in the UI rather than in the VS Code terminal. This will be done over several PRs.
- Added tests to verify:
- it spawns a `stripe logs tail` process
- it reuses the process if it already exists
- it passes flags to the process
- it ends the process
=> Add methods for spawning and ending a Stripe CLI child process (only support `stripe logs tail` for now)

config/api_ref/patterns.json, src/stripeLanguageServer/client.ts, src/stripeLanguageServer/server.ts, src/stripeLanguageServer/utils.ts
* Updated the server to lookup the pattern based on the stripe-normalized lang (i.e. javascript -> node).
* Updated the message to say 'See this method...' instead of 'See ${methodMatch}'.
The patterns now match on opening parentheses of the method so this showed up as 'See balance.Get( in the...'.
This config already has manual overrides applied -- the PR for that in the generator is coming soon. 
Screenshots:
=> Adding API reference config files for all langs (-dotnet)

package.json
Before: Start logs streaming with the command palette command `stripe.openLogsStreaming`
After: Start logs streaming with `stripe.startLogsStreaming`, stop with `stripe.stopLogsStreaming`
Tested manually that the commands work.
Tested that the commands are idempotent by running `ps -A | grep "stripe logs tail"` and checking there's at most one process.
I plan to update the docs page with these commands after this is released.
=> Add commands to command palette for starting and stopping logs streaming; remove dead command

src/stripeDashboardView.ts, src/stripeEventsView.ts, src/stripeHelpView.ts, src/stripeLogsView.ts, src/stripeTreeItem.ts
The constructor for this class is getting quite long, so we refactor it for maintainability.
Before: 
- The constructor is `constructor(label: string, commandString?: string, tooltip?: string, contextValue?: string)`.
After: 
- The constructor is `constructor(label: string, options: StripeTreeItemOptions = {})`, where `StripeTreeItemOptions` is a type that extends from `vscode.TreeItem`. This allows us (contributors to the repo) to have parameter info on hover:
- Existing tests pass.
- Manually verified each of the tree items' functionalities continue to work.
=> Refactor StripeTreeItem constructor

src/stripeEventsView.ts, src/stripeLogsView.ts, src/test/suite/utils.test.ts, src/utils.ts
Fixes #102.
Timestamps in `en`:
Timestamps in `en-gb`:
- ~~Added a test to verify formatting works in different locales~~
- Removed test due to it relying on the system timezone; no easy way to set it for the tests.
- Manually verified (see screenshots)
=> Add localized timestamps on hover to events and logs

package.json, src/commands.ts, src/extension.ts, src/stripeLogsView.ts
Add two new commands:
`stripe.openDashboardLogFromTreeItem` on left-clicking a log, open the log in the Dashboard.
`stripe.openDashboardLogFromTreeItemContextMenu`: on right-clicking a log, open a context menu with a link to the log in the Dashboard.
There are two commands because even though they are seemingly registered to the same object, unfortunately there are differences in how the arguments are passed.
=> Add link to the Dashboard for each API log

config/snippets/php.json
It gets interpreted as snippet-variables by VSCode instead of literal code.
Before:
After: 
And this error goes away:
=> Escape `$` from snippets

src/commands.ts, src/extension.ts, src/stripeDashboardView.ts, src/stripeEventsView.ts, src/stripeHelpView.ts, src/stripeLogsView.ts
The `activate` function is getting long, and some of the variable names are inconsistent, which adds friction when we want to add new features. This PR renames some variables for consistency, removes some redundant comments, and refactors how commands are registered.
Verified manually and with existing tests.
=> Refactor activate function

src/stripeClient.ts, src/test/suite/stripeClient.test.ts
Show a more prominent message to install the CLI. Deep-link to https://stripe.com/docs/stripe-cli#install. Rename some variables for clarity.
Before:
After:
Part of #187.
Updated existing test and manually verified.
=> Prompt CLI installation in modal

src/commands.ts, src/stripeLogsView.ts, src/stripeStreamingView.ts, src/test/suite/utils.test.ts
Moving out streaming management components from the stripeLogView file to an abstract class called StreamingViewDataProvider. The goal was to move the stream and state management to the abstract class, but not so strictly that we wouldn't be able to support future usecases.
This is a precursor to adding events streaming.
Manually tested the log streaming functionality.
=> Abstracting out streaming components of LogsView

src/stripeClient.ts, src/test/suite/stripeClient.test.ts, src/utils.ts
r? @vcheung-stripe @gracegoo-stripe 
cc @jhstrauss
With the help from #171, this should work for M1 macs. `process.arch` will return `arm64` (https://nodejs.org/api/process.html#process_process_arch) on the new devices instead of `x64`.
=> Detect processor arch and fork on that for darwin

package-lock.json, package.json
Changelog:
- Detect default brew install location for M1 Macs. The extension can now find your Stripe CLI at `/opt/homebrew/bin/stripe`.
- Add a button and command for clearing recent logs. The command `Stripe: Clear recent logs` is available through the command palette.
=> Bump v1.7.1 -> v1.7.2

package-lock.json, package.json, src/stripeClient.ts, test/suite/stripeClient.test.ts
Adding a min version check in stripeClient. The current recommended minimum version will be v1.5.12 because that has a required flag we want to use for the event streaming. 
This will prompt the user in bottom right, similar to the notifications we get when other extensions are out of date. It's not as intrusive as when the user does not have the CLI installed. I also added this check to the detectInstallation function because I figure we'd want to run this every time we use the CLI, similar to the installation notification.
When updating the min version to a non-existing v.1.13: 
This addresses https://github.com/stripe/vscode-stripe/issues/184
=> Adding min cli version detection

package.json, src/commands.ts, src/extension.ts, src/stripeClient.ts, src/stripeEventsView.ts
Replacing the recent events section with events streaming. Also got rid of the refreshing of events since that is no longer relevant. 
This depends on a specific release of the CLI: https://github.com/stripe/stripe-cli/pull/615. In fact, I think this is a good opportunity for us to add the [min version](https://github.com/stripe/vscode-stripe/issues/184) feature first before merging this PR in. 
This PR does not address the `openEventDetails` action. That action still uses the stripeClient to make another call to grab the event details from the id. I'll follow this PR up with another that stores the entire event object  in the tree so that `openEventDetails` does not need to use the CLI to fetch that info again. 
Before:
After:
=> Adding event streaming

src/commands.ts, src/extension.ts, src/stripeWorkspaceState.ts, test/suite/commands.test.ts, test/suite/stripeWorkspaceState.test.ts
fixes #168 
Before: We always pre-fill the "Start webhooks listening" input box with localhost:3000.
After: We pre-fill the input box with the user's most recent input. This is per-workspace as suggested in the issue.
Tested manually:
- clicking "Start webhooks listening"
- invoking the command through the debugger
- invoking the command through the command palette
- this actually didn't work before this PR
=> Save user input to Start webhooks listening

src/extension.ts, src/stripeClient.ts, test/suite/stripeClient.test.ts
Previously, we had to know to call `getCLIPath` instead of using `this.cliPath` because the former actually kicked off the function that populates `this.cliPath`. This commit updates the stripeClient object to kick off the installation detection in the constructor and changes the cliPath to be a promise so that the member variable will always be updated at least once.
The getCLIPath still exists as a wrapper function clients can call. It will re-check the installation path before vending it in case it is deleted within the lifespan of stripeClient. I also updated this function to verify the version and authentication before vending it as well.
In addition:
* Adding extensionContext to StripeClient for future use with telemetry.
* Removing some dead code
Updated unit tests and manually …
=> Deleting unused code and updating cliPath initialization

package-lock.json, package.json, src/commands.ts, src/extension.ts, src/stripeClient.ts, src/stripeTerminal.ts, src/utils.ts, test/suite/commands.test.ts, test/suite/stripeClient.test.ts, test/suite/stripeTerminal.test.ts, test/suite/utils.test.ts
Certain commands were not working on Windows, specifically the commands that involve sending text to the vscode integrated terminal: Trigger new event, Start webhooks listening*, etc. There was no problem on Mac or Linux.
Some context: some of these commands are long running (e.g. Start webhooks listening) and some are short running (e.g. Trigger new event). We initially wanted those short running commands to reuse one terminal rather than splitting off a new one every time. Imagine if you wanted to trigger `checkout.session.completed` twenty times, you wouldn't want twenty terminals to appear.
It turned out there were vscode api limitations with the integrated terminal. We couldn't easily figure out what process was running on which terminal, which meant the extension couldn't easily …
=> Land windows fix

src/surveyPrompt.ts, test/suite/surveyPrompt.test.ts
I've noticed a few survey responses coming in where the feedback is something like "I've already taken this survey". Adding in a concept of survey versioning so that we don't spam folks who've already taken the survey when their 12 weeks expire.
We keep the 12 week limit in there so that we don't spam the same user again within that period of time even if we release a new version of the Survey.
Users are still able to open the survey and leave feedback any time they want by clicking "Rate and provide feedback".
=> Adding a survey version to prompt check

src/extension.ts
It spams logs in development and in unit tests. When we are debugging telemetry we can always swap out this NoOp with the logging implementation.
=> Remove LocalTelemetry logging for development mode

test/suite/commands.test.ts, test/suite/stripeLinter.test.ts, test/suite/telemetry.test.ts
- Some telemetry tests were failing because of timeout. They make several vscode API calls, which not only slows down the tests, but also makes the test output very noisy. This PR replaces those calls with stubs.
- Those vscode API calls relied on a dummy workspace. Since we don't make those calls anymore, I removed the dummy workspace folder.
- I also updated a linter test that was failing after removing the dummy workspace folder.
=> Fix tests that use workspace

package.json, src/stripeClient.ts, src/stripeTerminal.ts, test/suite/stripeClient.test.ts, test/suite/stripeTerminal.test.ts
fixes #57 
When the CLI can't be detected, show a welcome view on startup:
After CLI is installed, refresh to see the logs and events views:
https://user-images.githubusercontent.com/71457708/117872968-21dc1300-b254-11eb-840e-ddb01a0af05b.mov
Authentication is not a part of this flow. We may want to improve this later:
https://user-images.githubusercontent.com/71457708/117872967-21437c80-b254-11eb-93d1-70b3938abcdb.mov
If the CLI is uninstalled while the extension is active, commands will fail and the welcome view will be focused:
https://user-images.githubusercontent.com/71457708/117872961-20aae600-b254-11eb-8909-51cdb269614d.mov
Same scenario, but the stripe extension is not in view. The welcome view will be focused:
https://user-images.githubusercontent.com/71457708/117872955-1e488c00-b …
=> Use a welcome view instead of modal to prompt CLI installation

src/commands.ts, src/stripeEventsView.ts
- Changed command name: **Start webhooks listening** ->  **Forward events to your local machine** (closes #70)
- Added a tooltip on hover: "Forward webhook events from Stripe to your local machine by connecting directly to Stripe's API." (fixes #113)
- Because we changed the name of the button to be "Forward events ...", remove the prompt that asks if you want to forward events (because obviously you do)
- Lowercased for consistency: **Start streaming Events** -> **Start streaming events**
Before:
After:
=> Update events buttons

test/suite/stripeClient.test.ts
These tests are reading the actual `stripe.cliInstallpath` on whatever system they're running on, which causes them to fail sometimes. This stubs the `getConfiguration` call so that the tests should always pass correctly.
=> Fix tests that sometimes fail when a custom CLI path is set

package.json, src/commands.ts, src/stripeDebugProvider.ts
fixes #169 
- When clicking **Forward events to your local machine**, when a user provides any URL that starts with https, ask if they want to skip certificate verification.
- For the debug configuration, add a `skipVerify` option that can be set in the launch.json.
Tested manually.
**Forward events to your local machine**:
https://user-images.githubusercontent.com/71457708/120684026-1d6dd900-c453-11eb-84ae-b18204e4db59.mov
Debugger config:
https://user-images.githubusercontent.com/71457708/120683847-f1eaee80-c452-11eb-8a8e-58e89981323d.mov
=> For `stripe.openWebhooksListen`, allow skipping certificate verification for https URLs

src/stripeLinter.ts, test/suite/stripeLinter.test.ts
The redaction change is targeted to protect against the specific redacted format that Stripe returns which looks something like "sk_live_aa********************1234".
It does not attempt to detect other potential ways users can modify the keys  nor actually validate that the key is real.
This change fixes https://github.com/stripe/vscode-stripe/issues/220 and https://github.com/stripe/vscode-stripe/issues/222
.env file before:
after:
redacted keys before:
after:
=> Linter Updates: Ignore .env files and redacted keys 

package.json
r? @vcheung-stripe 
cc? @stripe/developer-products
fixes #244 
Hide the quick links and feedback sections when the user doesn't have the StripeCLI installed. When the user doesn't have it installed we show the welcome view. 
When the CLI is uninstalled: 
When the CLI is installed:
=> Hides views when on the welcome view

src/commands.ts
When you launch cmd+shift+p and run “Start webhooks event listening” the options can be null because the user will type them in. This adds a null check. 
###Testing 
Verified manually without check: 
With check everything runs: 
r? @vcheung-stripe 
cc @stripe/developer-products
=> Adding null check for skipverify

package.json, src/stripeQuickLinksView.ts
the command palette equivalent of Stripe samples should be: "Start with a Stripe Sample" to match what shows up in the panel.
Change the Command Palette text from “Start webhooks events listening with CLI” to “Forward webhook events to your local machine”, so that the UI ~ aligns
“events”, “API keys”, and “webhooks” should all be lowercase in the command palette
“Start with a Stripe sample” ← lowercase Sample
Manually tested 
r? @gracegoo-stripe 
fixes #250
=> Fix naming

package.json, src/commands.ts, src/extension.ts, src/stripeHelpView.ts, src/stripeQuickLinksView.ts, src/stripeSamplesView.ts
- Move the samples out into its own view. Panel should be: Events, Logs, Samples, Quick Links, Help and Feedback
- Auto-collapse the quick links and help and feedback section.
- Remove "Find code samples" from the help and feedback link. This belongs in the context of the Stripe Samples workflow.
Manually tested:
fixes #249 
r? @vcheung-stripe
=> Moving stripe samples to it's own menu

src/stripeTerminal.ts
fixes #266 
See the linked issue for an explanation.
=> Fix split terminal bug

src/commands.ts
r? @vcheung-stripe 
fixes #248 updating the text to show connect vs account more prominently. Given a lack of better UX text is all we can do unless we go full custom.
=> Updating the text for the webhooks prompt

.vscode/tasks.json, package.json, src/languageServerClient.ts
This commit adds a new npm script target that calls the `dotnet publish` command to place all necessary libs into the dist/stripeDotnetLanguageServer folder which we can then access from the client. We are excluding the test project from being included in the publishing. 
I also updated the task.json as well to use the npm script. 
Note -- this did not need to be an npm script at all, we could have just added a bash script that has the same contents and called it, but I figured it'll just be easier to keep track of if all our build steps were in the same place. 
1. Made sure the language server can startup via the debugger launcher 
2. Packaged up the extension with `vsce package`, manually installed it, and made sure the language server can start up.
=> Add publishing step for dotnet language server

src/stripeSamples.ts
From the API doc: 
The *difference* between `Uri#parse` and `Uri#file` is that the latter treats the argument as path, not as stringified-uri.
Also verified that opening samples still works on mac.
Before:
https://user-images.githubusercontent.com/2405770/122610962-5bfbba00-d035-11eb-8661-352549cae4d6.mp4
After:
https://user-images.githubusercontent.com/2405770/122610964-5dc57d80-d035-11eb-8f50-d2c9c16fde5a.mp4
=> Fixing Stripe Samples folder opening on Windows

src/languageServerClient.ts, test/suite/languageServerClient.test.ts
Fixes https://github.com/stripe/vscode-stripe/issues/287.
dotnet < 6.0 is not supported for native M1 so this commit adds a check to not even attempt to acquire it.
Given that dotnet is not supported, we don't expect this path to be hit anyway but adding telemetry to get some numbers.
* Also added some unit tests for this change and also fixed the unit tests for the `getDotnetProjectFiles` and added them back in.
=> Do not try to acquire dotnet runtime if we are on M1 macs 

src/languageServerClient.ts
If the C# server fails to start up for an unrecoverable reason, restarting it will cause repeated crashes:
https://github.com/stripe/vscode-stripe/issues/292
This does not address the original root cause of the crash, but will mitigate the repeated crashes users will experience on mac.
=> Do not restart if C# server exits

test/suite/stripeSamples.test.ts
A test recently began to fail in some platforms intermittently after 1.58.1. Upon [investigation with logs](https://github.com/stripe/vscode-stripe/actions/runs/1028044302), the failing test was never getting the quick pick item selections. Running the failing test by itself would [pass](https://github.com/stripe/vscode-stripe/actions/runs/1028125520). 
My guess is that something changed with the showInformation window that will cause it to hang if we don't pick a prompted selection. I made the window return quickly with a selected value which then allowed the subsequent test to run as it did before.
=> Resolving samples information box

test/suite/commands.test.ts
The openSurvey test began to fail recently for windows. Inspection with the timer shows that the osName() function was taking much longer on the windows machine. On mac and linux it is on the order of single digit milliseconds and for windows it can span many seconds. This commit fixes the testing timeout issue by mocking out this call.
I am still concerned that the call actually takes that long on windows machines and how that's impacting latency, especially since we use this constantly for telemetry. I'll continue investigating this. 
Before: https://github.com/stripe/vscode-stripe/runs/3089718394?check_suite_focus=true
```
Telemetry: 0
getExtensionInfo: 0
get OSName: 21943
encode platform: 0
encode version: 0
encode version: 0
encode version: 0
form query string: 0
open link: 0
update …
```
=> stubbing out osName() in commands test

src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs, src/stripeDotnetLanguageServer/stripe.LanguageServer/stripe.LanguageServer.csproj
Updated dotnet packages based on the latest run of dependabot. 
We don't have automated tests for the language server right now, so I manually tested out the API reference functionality.
=> Updating packages and removing unused code

src/telemetry.ts
osName() can sometimes take a while in the Windows Server 2019 OS we use for CI. We use it in `sendEvent` multiple times so this change initializes it once during construction of the telemetry object.
=> initializing osName once in telemetry

src/commands.ts, src/extension.ts, test/suite/commands.test.ts
context: https://github.com/stripe/vscode-stripe/issues/217
Supported list of events was a static list in our extension:
`vscode-stripe/src/commands.ts`
```
supportedEvents: string[] = [ 
We need a better way to keep this in sync. Couple of options:
```
To dynamically retrieve the supported triggered events list, make a call to the CLI gPRC service at trigger event click. if the list is failed to be retrieved, then fall back to the old static list and outputs an warning to output window
=> Dynamically retrieve supported triggers list from CLI

package.json, src/languageServerClient.ts, src/stripeJavaLanguageClient/utils.ts
https://jira.corp.stripe.com/browse/DX-6964
better user experience when JDK version is missing
=> DX6964: store java home path in user settings

test/suite/stripeLinter.test.ts
r? @etsai-stripe 
These tests have been intermittently failing due to timeouts: https://github.com/stripe/vscode-stripe/runs/4121204401?check_suite_focus=true
The open and show document functions can take a couple of seconds in the worst case scenario which will cause the test to timeout (the default is 2 seconds). Even for ones that do pass, we always come close to the timeout in the first two test cases.
See logs added here: https://github.com/stripe/vscode-stripe/runs/4159081815?check_suite_focus=true. 
```
Doc open took: 245 ms
Doc show took: 126 ms
Test set up took 374 ms
Linter construction took 1 ms
File is ignored by git? true
Linter.activate took  2 ms
Test cleanup  1 ms
✔ Editor content is not searched when file is git-ignored (379ms)
```
=> Increasing timeouts for linter tests

package-lock.json, package.json
tested by installing the v2.0.10 .vsix file
addressing issue https://github.com/stripe/vscode-stripe/issues/439
=> vscode release v2.0.10

src/stripeSamples.ts, test/suite/stripeSamples.test.ts
https://jira.corp.stripe.com/browse/DX-6943
allow user to define the name to download the sample as. use original sample name by default.
=> dx-6943: allow user defined sample name

package-lock.json, package.json
r? @etsai-stripe 
This is currently the latest version we can update to as the actual latest version converts this package to a pure ES module. 
See comments here: https://github.com/stripe/vscode-stripe/pull/438
Same for the execa package: https://github.com/stripe/vscode-stripe/pull/448
=> Updating os-name to 4.0.1

src/languageServerClient.ts, src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs
Note: I was able to reproduce the error by deleting the sdk folders under `/usr/local/share/dotnet/sdk` -- there may be other conditions where folks have an sdk inside the folder but the msbuild tool can still not be found.
1. Updated the error message return from the server which will directly show up on the output channel.
2. Overrode the error function to not show the notification box because without this change it'll still show the generic message as below. Another alternative was to update the `showNotificationMessage` but the closed event does not accept any messages from the server, so we would be changing the message for all notifications. 
https://github.com/microsoft/vscode-languageserver-node/blob/756cf416e98bc9ce843416cf1c03881ddd1ef322/client/src/common/client.ts#L310
Before: …
=> Outputting a better error message when the MSBuild tool cannot be found

src/telemetry.ts, test/suite/telemetry.test.ts
This API also respects the telemetry flag passed in through the CLI when the user starts their code session: https://code.visualstudio.com/updates/v1_55#_telemetry-enablement-api
Regarding the tests, the original tests were not working because it would fail at the line below with an error saying that the update function did not exist.
```
await vscode.workspace.getConfiguration('telemetry').update('stripe', undefined);
```
This was because we stubbed out the result returned by `getConfiguration` and the stubbed result did not have it. However, we don't really need to call update to simulate a config change since we are calling the constructor which calls `areAllTelemetryConfigsEnabled` anyway. 
The reason why the tests did not pass was because we would reach the end of the test case …
=> Using the isTelemetryEnabled provided by VSCode and fixing unit tests

package-lock.json, package.json
And general dependency updates
Dependabot alert: https://github.com/stripe/vscode-stripe/security/dependabot
There is a transitive dependency on the vulnerable version of ansi-regex via grpc-tools:
```
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grpc-tools [dev] …
```
=> Forcing resolution for ansi-regex for sec vulnerability

package.json
This PR adds a `jsonValidation` entry to `package.json` that enables the Stripe App manifest schema [hosted in the Stripe Apps GitHub repo](https://github.com/stripe/stripe-apps/blob/main/schema/stripe-app.schema.json) to validate `stripe-app.json`.
=> Add stripe-app.json schema link

package.json
Add a `jsonValidation` entry to `package.json` that enables the Stripe App local manifest schema [hosted in the Stripe Apps github repo](https://github.com/stripe/stripe-apps/blob/main/schema/stripe-app-local.schema.json) to validate `stripe-app.*.json` named (e.g. `stripe-app.dev.json`) local manifest files.
=> Add stripe-app.*.json schema link

.github/workflows/build.yml, README.md, package-lock.json, package.json, test/runTest.ts
This updates the README with instructions to how to get the extension to run.
It also updates the minimum VSCode version to allow us to use newer APIs.
It also upgrades the tests to pass in Github Actions. This required some debugging, but it ended up being because I needed to upgrade `vscode-test` to a newer version and update the platform for windows. In the future, as we update the extension, the first spot we should look should be outdated NPM packages.
I did not bump the package version just yet because I do not want to make a release (no new functionality has been added).
=> Upgrade extension to latest testing libraries, update README, and VSCode version

src/shellEscape.ts, src/stripeTerminal.ts, test/suite/shellEscape.test.ts
Addresses the bug where command injection can be used in the projectName value in workspace settings, by escaping strings passed in as arguments. 
https://security-insights.corp.stripe.com/pathfinder/sats/SAT-10878
The solution is based on [shell-escape](https://www.npmjs.com/package/shell-escape), but also adapted to handle Windows computers. This was tested on both Windows and Mac.
=> Escape strings to be passed in as arguments.

src/shellEscape.ts, test/suite/shellEscape.test.ts
escapes backslash input, added a test
=> fix: escape backslash input

test/suite/shellEscape.test.ts
Reverts `test.only()` calls to `test()` to fix broken test runner.
=> Fix test.only calls so test suite can run

src/stripeClient.ts
This fixes an issue where the extension always prompts for login when you have a project name set.
To check if you're authenticated, we run `stripe config --list` and parse the TOML output. The problem is when you set a project name, `stripe config --list` doesn't return valid TOML, so we don't know that you're authenticated. 
This fixes it by explicitly setting `stripe config --list --project-name default` which prints out the config file verbatim so that it's always valid TOML.
=> Fix auth check

.gitignore, package.json, src/stripeTerminal.ts, test/suite/stripeTerminal.test.ts
This escapes more characters in the project name configuration value so that we keep the input correct and useful.
=> Escape characters in project name

package-lock.json, package.json, test/suite/stripeDaemon.test.ts
This PR upgrades vscode-stripe's grpc-js dependency to 1.12. There's test coverage that appears to assert things based on the internals of the generated gRPC client constructor, and so this PR fixes those tests as well.
I changed our version specificity for grpc-js to be more precise since we have this test dependency on those internals. Once we figure out how to test this more robustly and not rely on those internals, we can loosen the restriction again.
=> Upgrades grpc-js to 1.12 and fixes resulting test failure
