package-lock.json
package.json

Update version to 0.5.1. This is to possibly fix an accidental release to a bad version number 1.6.8.

Update version to 0.5.1

---

src/stripeClient.ts
src/test/suite/stripeClient.test.ts

When the extension starts up, it is not respecting the `stripe.cliInstallPath` setting to detect if the Stripe CLI is installed. This change fixes this issue. This is related to (but does not fix) #92, which requires respecting the `stripe.cliInstallPath` setting when running stripe commands in the integrated terminal.
For example, I moved `/usr/local/bin/stripe` to `/usr/local/bin/stripe2`. With this change, the extension now asks me to install when using `/usr/local/bin/stripe`, but not `/usr/local/bin/stripe2`:
Fixes #133.
- Unit tests.
- Manually verify by moving my CLI binary, setting `stripe.cliInstallPath` to the new path, and seeing that I'm not notified to install the CLI.

Detect that the CLI is installed at a custom path

---

package-lock.json
package.json

Upgrading to 1.7.0

---

.eslintrc.js
src/commands.ts
src/extension.ts
src/resources.ts
src/stripeClient.ts
src/stripeLanguageServer/patterns.ts
src/stripeLogsView.ts
src/test/suite/stripeClient.test.ts

Invoked prettier on the remaining source files. I found a conflicting eslint rule, which I removed.

Format with prettier/eslint

---

package-lock.json
package.json

Summary of changes since 1.7.0:
* Removed dependency on the VSCode Git extension
* Request log streaming in the Logs View UI
* Adding API reference support for all langs except .NET
* Adding snippet support for all langs
* Localized timestamps
* Migrated to use ThemeIcon from VSCode

Upgrading to 1.7.1

---

package.json
src/commands.ts
src/extension.ts
src/stripeStreamingView.ts

Adds an option to clear items from the Recent logs section.

Adding a Clear Recent Logs button

---

package-lock.json
package.json

* Adding webpack bundling
* Adding min cli version detection
* Adding event streaming
The webpack change will also address https://github.com/stripe/vscode-stripe/issues/201

Upgrading to 1.7.4

---

package.json
src/commands.ts
src/extension.ts
src/stripeHelpView.ts

Add "Find code samples" link and command

---

.github/workflows/build.yml

We were running this on ubuntu-latest only. Updated to run on ubuntu-latest, macos-latest, and windows-latest. Also updated to run on pushes and PRs to all branches instead of only master.

Update GH action to build and test on multiple OSes

---

src/commands.ts
src/extension.ts
src/surveyPrompt.ts
test/suite/commands.test.ts
test/suite/surveyPrompt.test.ts

Addresses the other half of https://github.com/stripe/vscode-stripe/issues/145

Update survey prompt settings on open survey command

---

src/commands.ts

Motivation: https://github.com/stripe/stripe-cli/pull/588#issuecomment-816724419
We probably need a better way to sync these up: https://github.com/stripe/vscode-stripe/issues/217.

Add more supported triggers

---

package-lock.json
package.json

The previous version was incompatible with remark 13.0.0.
See https://github.com/unlight/remark-package-dependencies/issues/2 for more details

Upgrade remark-package-dependencies to 2.0.1

---

.github/workflows/build.yml

This runs the linter before each test.

Adding linting to the GH action

---

.github/workflows/tag.yml

Add action to create a tag when package.json version changes

---

config/snippets/dotnet.json
config/snippets/go.json
config/snippets/java.json
config/snippets/node.json
config/snippets/php.json
config/snippets/python.json
config/snippets/ruby.json

Updating snippet configs after update to generation script.
Tested for no errors parsing the config during start-up, and ran through just a few snippets to make sure they still work

Adding new configs containing manual snippets

---

src/stripeClient.ts

fixes #216
Will merge once CLI upgrading instructions are available at https://stripe.com/docs/stripe-cli#upgrade.

Update link to upgrade CLI

---

package-lock.json

package-lock.json was out of date.

Regen package-lock.json

---

package-lock.json
package.json

1.7.7 release

---

src/stripeSamples.ts

fixes #251 
Tested manually.
Now, the integrations prompt appears right away, and a progress indicator appears if it takes too long to load. You can see the progress indicator briefly in this video, underneath the input box.
https://user-images.githubusercontent.com/71457708/121064120-0513fc00-c77c-11eb-9582-452649c55d20.mov

Show progress indicator while a sample's integrations are loading

---

src/stripeClient.ts

Update the text for when a user needs to update Stripe CLI versions. 
Text change, no functionality. 
r? @gracegoo-stripe 
cc? @stripe/developer-products

Updating update text

---

src/commands.ts

r? @vcheung-stripe 
Fixes #264

Fix startsWith undefined error 

---

.vscode/launch.json
src/extension.ts
src/languageServerClient.ts
src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs
test/suite/languageServerClient.test.ts

I also moved the language server client out of the stripeLanguageServer directory because I think it belongs in the extension code.
https://user-images.githubusercontent.com/75757829/122124584-552a3880-cde4-11eb-8146-5b2cd3161b26.mp4

Adding conditional language server startup and passing in project from user workspace

---

src/languageServerClient.ts

Addresses part of https://github.com/stripe/vscode-stripe/issues/287
We want to exclude common folders that are not part of the user's workspace when we try to detect solutions. There may be more we want to add to the exclusion list later on. 
Before this change, this file triggering the dotnet server startup `node_modules/node-sass/src/libsass/win/libsass.sln` but after this change it does not

Adding exclude pattern for dotnet project finder

---

package-lock.json
package.json

* Adding exclude pattern for dotnet project finder

releasing v2.0.2

---

package-lock.json
package.json

* Do not restart if C# server exits. (#293)
* Do not try to acquire dotnet runtime if we are on M1 macs  (#291)

releasing 2.0.3

---

package-lock.json

Updating path-parse based on security alert: https://github.com/stripe/vscode-stripe/security/dependabot/package-lock.json/path-parse/open

updating path-parse

---

package-lock.json

Updating a bunch of the npm packages. The rest are upgrades that will be a bit more involved so I'll tackle those separately.

Updating various packages

---

config/snippets/dotnet.json
config/snippets/go.json
config/snippets/java.json
config/snippets/node.json
config/snippets/php.json
config/snippets/python.json
config/snippets/ruby.json

Updating snippets using the generation scripts.

Updating snippets

---

package-lock.json
package.json

Notable change include: 
* Updated the code snippets
* Added the abilty to dynamically retrieve supported triggers using the CLI

Version 2.0.4

---

package.json
src/stripeJavaLanguageServer/extractServer.ts

DX-6802: download and extract jdt server

---

package.json
schemas/stripe.fixture.schema.json
src/commands.ts
src/extension.ts
src/utils.ts
test/suite/commands.test.ts
test/suite/utils.test.ts

https://jira.corp.stripe.com/browse/DX-6899
- add json schema validation
- finalize UX flow
- add tests

DX6899: Finalize prototype and add tests

---

package-lock.json
src/commands.ts
src/daemon/stripeDaemon.ts
src/extension.ts
src/stripeClient.ts
test/suite/commands.test.ts

This change updates the login flow to use the gPRC protocol and integrates the flow into the UI. 
https://user-images.githubusercontent.com/75757829/140431176-73c58014-cf37-4c80-9ab4-db07318cc990.mov

Migrate login flow to use gRPC 

---

package.json
src/languageServerClient.ts
src/stripeJavaLanguageClient/utils.ts
test/suite/languageServerClient.test.ts

- remove java package dependency:
https://github.com/stripe/vscode-stripe/issues/439
- java project not detected to trigger java lang support activation

remove extension dependency and detect java proj correctly

---

src/stripeSamples.ts
test/suite/stripeSamples.test.ts

https://jira.corp.stripe.com/browse/DX-6944
updated copy

update sample cloned successfully copy

---

src/stripeSamples.ts
test/suite/stripeSamples.test.ts

https://jira.corp.stripe.com/browse/DX-6942
open sample README in default browser after sample is done cloning

open sample readme in default browser

---

src/stripeDotnetLanguageServer/stripe.LanguageServer/stripe.LanguageServer.csproj

r? @etsai-stripe 
We need to update both of these together.
https://github.com/stripe/vscode-stripe/pull/432
https://github.com/stripe/vscode-stripe/pull/431
Tested out the hover over on a dotnet project.

Updating CodeAnalysis Lib

---

src/commands.ts
src/stripeSamples.ts
test/suite/stripeSamples.test.ts

fix master CI build failures
use information message to show cloning in progress because the progress bar doesnt show when it is downloading too fast
make triggering customized fixture a modal to be more obvious to user that they need to make a selection

fix master CI build failures

---

src/commands.ts

use generic CSAT form and pass in client data

---

src/rpc/logs_tail_pb.d.ts
src/rpc/logs_tail_pb.js

https://jira.corp.stripe.com/browse/DX-7103
updated logs tailing response

update proto files to show error insight in log tailing

---

test/suite/commands.test.ts

These two tests fail, which blocks other PRs from merging. Specifically, I want to merge in these two:
- https://github.com/stripe/vscode-stripe/pull/564
- https://github.com/stripe/vscode-stripe/pull/570

Fix race condition in a couple tests

---

src/stripeLinter.ts

https://github.com/stripe/vscode-stripe/issues/630

remove git warning for public keys

---

package-lock.json
package.json
src/commands.ts
src/extension.ts
src/stripeSamples.ts
test/suite/commands.test.ts

cc @stripe-internal/developer-products
r?
- Given a uri of format `vscode://stripe.vscode-stripe/createStripeSample?sample=${sample}&integration=${integration}`, initiate logic for "Start with a Stripe Sample" for the provided sample
- If sample/integration are missing, initiate logic for general "Start with a Stripe Sample" process
https://github.com/user-attachments/assets/d4125e8c-0130-4e16-b371-d34875445324
[DX-9523](https://jira.corp.stripe.com/browse/DX-9523)
Safe to revert unless specified otherwise

[workbench samples] Initiate logic to run the Sample wizard given uri

---

src/stripeJavaLanguageServer/extractServer.ts

- npm run java-server was causing this error when running `vsce package` and `vsce publish minor`
- checks that extraction is finished before unlinking
r? @vcheung-stripe

fix npm run java-server

---

README.md

Update README.md image links
